- hosts: devlinuxenvanter
  gather_facts: no
  ignore_errors: false
  tasks:
    - name: call yumrepo playbook
      include_tasks: yumrepo.yml
 
    - name: install necessary packeges to authenticate with AD
      command: yum install -y  sssd realmd oddjob oddjob-mkhomedir adcli samba-common samba-common-tools krb5-workstation openldap-clients policycoreutils-python nss-pam-ldapd 
      

    - name: LDAP authentication activate
      shell: authconfig --updateall --enableldap --enableldapauth --disableldaptls --ldapserver=ldap://* * *.com  --ldapbasedn="OU=LINUX,OU=Non Windows Servers,OU=AppServers,DC=* * *,DC=* * *,DC=com"
     

    - name: Take linux to domain 
      shell: echo {{svc_tfdomjoin}} | realm join --computer-ou="OU=LINUX,OU=Non Windows Servers,OU=AppServers,DC=* * *,DC=* * *,DC=com"  -U svc_tfdomjoin ***.com
      

    - name: firstly deny all domain users
      shell: realm deny --all
    
    - name: permit only  sistem and devops grups to login for dev,uat,preprod servers
      shell: realm permit -g devops@* * *.com  Sistem@* * *.com 

    - stat:
        path: /etc/sudoers.d/sudoers
      register: sudo

    - shell: touch /etc/sudoers.d/sudoers 
      when: sudo.stat.exists
 

    - name: dev,uat ve preprod sunucuları için  devops grubuna sudo yetkisi 
      blockinfile:
        path: /etc/sudoers.d/sudoers
        block: |
          %devops@intertech.denizbank.com    ALL=(ALL)       ALL
          %Sistem@intertech.denizbank.com    ALL=(ALL)       ALL
      ignore_errors: yes

    - name: Delete below lines
      lineinfile:
        path: /etc/sssd/sssd.conf
        state: absent
        line: '{{ item }}'
      with_items:
        - use_fully_qualified_names = True
        - fallback_homedir = /home/%u@%d

    - name: Added lines to sssd.conf 
      blockinfile:
        path: /etc/sssd/sssd.conf
        insertafter: "[domain/intertech.denizbank.com]"
        block: | 
          use_fully_qualified_names = False
          fallback_homedir = /home/%u

    - name: Restart service sssd to get changes
      service:
        name: sssd
        state: restarted
        enabled: yes
